CREATE TABLE bus
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capacity INTEGER                                 NOT NULL,
    CONSTRAINT pk_bus PRIMARY KEY (id)
);

CREATE TABLE city
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE trip
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    departure_id   BIGINT                                  NOT NULL,
    departure_time TIMESTAMP WITHOUT TIME ZONE,
    arrival_id     BIGINT                                  NOT NULL,
    arrival_time   TIMESTAMP WITHOUT TIME ZONE,
    price          DOUBLE PRECISION,
    bus_id         BIGINT                                  NOT NULL,
    free_seats     INTEGER,
    CONSTRAINT pk_trip PRIMARY KEY (id)
);

ALTER TABLE trip
    ADD CONSTRAINT FK_TRIP_ON_ARRIVAL FOREIGN KEY (arrival_id) REFERENCES city (id);

ALTER TABLE trip
    ADD CONSTRAINT FK_TRIP_ON_BUS FOREIGN KEY (bus_id) REFERENCES bus (id);

ALTER TABLE trip
    ADD CONSTRAINT FK_TRIP_ON_DEPARTURE FOREIGN KEY (departure_id) REFERENCES city (id);

CREATE TABLE reservation
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seats     INTEGER                                 NOT NULL,
    trip_id   BIGINT                                  NOT NULL,
    "user_id" BIGINT                                  NOT NULL,
    price     DOUBLE PRECISION,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_TRIP FOREIGN KEY (trip_id) REFERENCES trip (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_USER FOREIGN KEY ("user_id") REFERENCES "user" (id);
