import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-material-symbols/rounded";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import ServerProviders from "./serverProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServerProviders>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ServerProviders>
      </body>
    </html>
  );
}
