name: Tests & Sonar analysis

on:
  push:
    paths:
      - "HW1/backend/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./HW1/backend

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, test and analyze
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Firefox
        run: |
          sudo snap remove firefox
          
          wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

          echo '
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
          ' | sudo tee /etc/apt/preferences.d/mozilla

          sudo apt update
          sudo apt install firefox
      - name: Up containers
        env:
          CURRENCY_API_KEY: ${{ secrets.CURRENCY_API_KEY }}
        run: docker compose -f compose.prod.yaml up -d --build
        working-directory: ./HW1
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          CURRENCY_API_KEY: ${{ secrets.CURRENCY_API_KEY }}
        run: |
          SPRING_APPLICATION_JSON='{"currencyapi.apikey":"${CURRENCY_API_KEY}"}' \
          mvn -B verify failsafe:integration-test sonar:sonar \
          -Dsonar.projectKey=RGarrido03_TQS_107927_a65738b4-e7ac-47cd-a1f4-6be8a28ad274 -Dsonar.projectName='TQS_107927'
      - name: Down containers
        run: |
          docker compose -f compose.prod.yaml down --volumes
          docker builder prune -a -f
        working-directory: ./HW1
